### PR TITLE
Fix validation error using required/additionalProperties

### LINKED ISSUE #26: Validation returns "An operation is not implemented: something went wrong" for complex schema
Hi @erosb ,

While using this library against our test suite, I ran into a validation error on a complex schema.  Below is the code that returns the error.

```
package io.confluent.kafka.schemaregistry.json.schema;

import com.github.erosb.jsonsKema.IJsonValue;
import com.github.erosb.jsonsKema.JsonParseException;
import com.github.erosb.jsonsKema.JsonParser;
import com.github.erosb.jsonsKema.JsonValue;
import com.github.erosb.jsonsKema.Schema;
import com.github.erosb.jsonsKema.SchemaClient;
import com.github.erosb.jsonsKema.SchemaLoader;
import com.github.erosb.jsonsKema.SchemaLoaderConfig;
import com.github.erosb.jsonsKema.SchemaLoadingException;
import com.github.erosb.jsonsKema.Validator;
import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.UncheckedIOException;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Map;
import java.util.stream.Collectors;
import org.junit.Test;

public class ReferenceTest {

  private static final String DUMMY_BASE_URI = "dummy://input/";

  @Test
  public void testReferences() throws Exception {
    String doc = "{\n"
        + "  \"customerName\": \"acme\",\n"
        + "  \"acquireDate\": \"2020-12-12\"\n"
        + "}";
    JsonValue jsonValue = new JsonParser(doc).parse();

    String oneOfSchema = "{\n"
        + "  \"oneOf\": [\n"
        + "    { \"$ref\": \"customer.json\"},\n"
        + "    { \"$ref\": \"user.json\"}\n"
        + "  ]\n"
        + "}";
    String userSchema = "{\n"
        + "  \"type\": \"object\",\n"
        + "  \"additionalProperties\": false,\n"
        + "  \"properties\": {\n"
        + "    \"name\": {\n"
        + "      \"type\": \"string\"\n"
        + "    },\n"
        + "    \"age\": {\n"
        + "      \"type\": \"integer\",\n"
        + "      \"minimum\": 0\n"
        + "    }\n"
        + "  },\n"
        + "  \"required\": [\n"
        + "    \"age\"\n"
        + "  ]\n"
        + "}\n";
    String customerSchema = "{\n"
        + "  \"type\": \"object\",\n"
        + "  \"additionalProperties\": false,\n"
        + "  \"properties\": {\n"
        + "    \"customerName\": {\n"
        + "      \"type\": \"string\"\n"
        + "    },\n"
        + "    \"acquireDate\": {\n"
        + "      \"type\": \"string\"\n"
        + "    }\n"
        + "  }\n"
        + "}\n";

    Map<URI, String> refs = new HashMap<>();
    refs.put(new URI(DUMMY_BASE_URI + "user.json"), userSchema);
    refs.put(new URI(DUMMY_BASE_URI + "customer.json"), customerSchema);

    SchemaLoaderConfig config = new SchemaLoaderConfig(
        new ReferenceSchemaClient(refs), DUMMY_BASE_URI);

    JsonValue schemaJson = new JsonParser(oneOfSchema).parse();

    Schema loadedSchema = new SchemaLoader(schemaJson, config).load();
    Validator validator = Validator.forSchema(loadedSchema);
    validator.validate(jsonValue);
  }

  public static class ReferenceSchemaClient implements SchemaClient {

    private Map<URI, String> references;

    public ReferenceSchemaClient(Map<URI, String> references) {
      this.references = references;
    }

    @Override
    public InputStream get(URI uri) {
      String reference = references.get(uri);
      if (reference == null) {
        throw new UncheckedIOException(new FileNotFoundException(uri.toString()));
      }
      return new ByteArrayInputStream(reference.getBytes(StandardCharsets.UTF_8));
    }

    @Override
    public IJsonValue getParsed(URI uri) {
      BufferedReader reader = new BufferedReader(new InputStreamReader(get(uri)));
      String string = reader.lines().collect(Collectors.joining());
      try {
        return new JsonParser(string, uri).parse();
      } catch (JsonParseException ex) {
        throw new SchemaLoadingException("failed to parse json content returned from $uri", ex);
      }
    }
  }
}
```

Oddly, if I remove `"required": ["age"]` from `userSchema`, then the "something went wrong" error does not appear.

### PR DESCRIPTION
**Pull request by rayokota**
This fixes #26

### CODE REVIEW

**Comment by rayokota** [comment]
Here is a smaller test case than that in #26 that reproduces the problem:

```
@Test
  public void testReferences() throws Exception {
    String doc = "{\n"
        + "  \"customerName\": \"acme\",\n"
        + "  \"acquireDate\": \"2020-12-12\"\n"
        + "}";
    JsonValue jsonValue = new JsonParser(doc).parse();

    String userSchema = "{\n"
        + "  \"type\": \"object\",\n"
        + "  \"properties\": {\n"
        + "    \"age\": {\n"
        + "      \"type\": \"integer\",\n"
        + "      \"minimum\": 0\n"
        + "    }\n"
        + "  },\n"
        + "  \"additionalProperties\": false,\n"
        + "  \"required\": [\n"
        + "    \"age\"\n"
        + "  ]\n"
        + "}\n";

    JsonValue schemaJson = new JsonParser(userSchema).parse();

    Schema loadedSchema = new SchemaLoader(schemaJson).load();
    Validator validator = Validator.forSchema(loadedSchema);
    validator.validate(jsonValue);
  }
 ```

If the `additionalProperties` and `required` statements are switched, the problem does not arise

**Comment by rayokota** [comment]
The reason that the problem does not arise with `required` and `additionalProperties` in that order (as opposed to them being switched) is that in this case the following call is made:  `RequiredValidationFailure.join(AggregatingValidationFailure instance)`.   This returns a new `AggregatingValidationFailure`.  

However, when `additionalProperties` and `required` are in that order, then the following call is made: `AggregatingValidationFailure.join(RequiredValidationFailure instance)`.  This complains because the failures have different parents.  Instead of erroring out, it should just delegate to `super.join()`, which is the same behavior when the arguments are switched.

**Comment by rayokota** [comment]
@erosb , Question:  should the following code also delegate to `super.join`?
```
         if (instance != this.instance) {
             TODO("something went wrong: $instance vs ${this.instance}")
         }
```

**Comment by rayokota** [comment]
With the fix, here is the output when `additionalProperties` is before `required` (which used to error):

```
Line 1, character 1: multiple validation failures
Keyword: null
Schema pointer: #
Schema location: Line 1, character 1
Instance pointer: #
Instance location: Line 1, character 1
Causes:

	Line 1, character 1: multiple validation failures
	Keyword: null
	Schema pointer: #/additionalProperties
	Schema location: Line 9, character 3
	Instance pointer: #
	Instance location: Line 1, character 1
Causes:

		Line 2, character 19: false schema always fails
		Keyword: false
		Schema pointer: #/additionalProperties
		Schema location: Line 9, character 27
		Instance pointer: #/customerName
		Instance location: Line 2, character 19

		Line 3, character 18: false schema always fails
		Keyword: false
		Schema pointer: #/additionalProperties
		Schema location: Line 9, character 27
		Instance pointer: #/acquireDate
		Instance location: Line 3, character 18

	Line 1, character 1: required properties are missing: age
	Keyword: required
	Schema pointer: #/required
	Schema location: Line 10, character 3
	Instance pointer: #
	Instance location: Line 1, character 1
```

And here is the output when `required` is before `additionalProperties` (which works before and after the fix):

```
Line 1, character 1: multiple validation failures
Keyword: null
Schema pointer: #
Schema location: Line 1, character 1
Instance pointer: #
Instance location: Line 1, character 1
Causes:

	Line 1, character 1: required properties are missing: age
	Keyword: required
	Schema pointer: #/required
	Schema location: Line 9, character 3
	Instance pointer: #
	Instance location: Line 1, character 1

	Line 1, character 1: multiple validation failures
	Keyword: null
	Schema pointer: #/additionalProperties
	Schema location: Line 12, character 3
	Instance pointer: #
	Instance location: Line 1, character 1
Causes:

		Line 2, character 19: false schema always fails
		Keyword: false
		Schema pointer: #/additionalProperties
		Schema location: Line 12, character 27
		Instance pointer: #/customerName
		Instance location: Line 2, character 19

		Line 3, character 18: false schema always fails
		Keyword: false
		Schema pointer: #/additionalProperties
		Schema location: Line 12, character 27
		Instance pointer: #/acquireDate
		Instance location: Line 3, character 18
```

**Comment by erosb** [comment]
Hello @rayokota I added an other fix in this commit: https://github.com/erosb/json-sKema/compare/master...issue-26-other-attempt

This way, the `Issue26Test` will print the following json:
```
{
  "instanceRef": "#",
  "schemaRef": "#/additionalProperties",
  "message": "multiple validation failures",
  "causes": [
    {
      "instanceRef": "#/customerName",
      "schemaRef": "#/additionalProperties",
      "message": "false schema always fails",
      "keyword": "false"
    },
    {
      "instanceRef": "#/acquireDate",
      "schemaRef": "#/additionalProperties",
      "message": "false schema always fails",
      "keyword": "false"
    },
    {
      "instanceRef": "#",
      "schemaRef": "#/required",
      "message": "required properties are missing: age",
      "keyword": "required"
    }
  ]
}
```

I think this is a reasonable structure. Are you OK with this?

**Comment by rayokota** [comment]
@erosb , yes that works for me.  Thanks for looking into it!  I'll close this PR.

**Pull request closed without merging**
